ALTER TABLE users
    ADD COLUMN uuid UUID NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    ADD COLUMN status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    ADD COLUMN last_login_at TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT NOW(),
    ADD COLUMN deleted_at TIMESTAMP;
